In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [3]:
mnist = fetch_openml('mnist_784')

C:\Users\taqua\miniconda3\lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
N, d = mnist.data.shape
print("Total {:d} samples, each has {:d} pixels.".format(N, d))

Total 70000 samples, each has 784 pixels.


In [5]:
X_all = mnist.data
y_all = mnist.target

In [6]:
X_0 = X_all.loc[np.where(y_all == '0')[0]]  # all digit 0
X_0

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
21        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
34        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
37        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
51        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69952     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69962     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69964     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69983     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69993     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
21         0.0  ...       0.0       0.0       0.0       0.0       0.0   
34         0.0  ...       0.0       0.0       0.0       0.0       0.0   
37         0.0  ...       0.0       0.0       0.0       0.0       0.0   
51         0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69952      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69962      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69964      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69983      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69993      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
1           0.0       0.0       0.0       0.0       0.0  
21          0.0       0.0       0.0       0.0       0.0  
34          0.0       0.0       0.0       0.0       0.0  
37          0.0       0.0       0.0       0.0       0.0  
51          0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69952       0.0       0.0       0.0       0.0       0.0  
69962       0.0       0.0       0.0       0.0       0.0  
69964       0.0       0.0       0.0       0.0       0.0  
69983       0.0       0.0       0.0       0.0       0.0  
69993       0.0       0.0       0.0       0.0       0.0  

[6903 rows x 784 columns]

In [7]:
X_3 = X_all.loc[np.where(y_all == '3')[0]]  # all digit 3
X_3

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
7         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
12        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
27        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
30        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69944     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69965     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69975     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69986     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
7          0.0  ...       0.0       0.0       0.0       0.0       0.0   
10         0.0  ...       0.0       0.0       0.0       0.0       0.0   
12         0.0  ...       0.0       0.0       0.0       0.0       0.0   
27         0.0  ...       0.0       0.0       0.0       0.0       0.0   
30         0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69944      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69965      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69975      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69986      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
7           0.0       0.0       0.0       0.0       0.0  
10          0.0       0.0       0.0       0.0       0.0  
12          0.0       0.0       0.0       0.0       0.0  
27          0.0       0.0       0.0       0.0       0.0  
30          0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69944       0.0       0.0       0.0       0.0       0.0  
69965       0.0       0.0       0.0       0.0       0.0  
69975       0.0       0.0       0.0       0.0       0.0  
69986       0.0       0.0       0.0       0.0       0.0  
69996       0.0       0.0       0.0       0.0       0.0  

[7141 rows x 784 columns]

In [8]:



X_1 = X_all.loc[np.where(y_all == '1')[0]]  # all digit 1
X_2 = X_all.loc[np.where(y_all == '2')[0]]  # all digit 2

X_4 = X_all.loc[np.where(y_all == '4')[0]]  # all digit 4
X_5 = X_all.loc[np.where(y_all == '5')[0]]  # all digit 5
X_6 = X_all.loc[np.where(y_all == '6')[0]]  # all digit 6
X_7 = X_all.loc[np.where(y_all == '7')[0]]  # all digit 7
X_8 = X_all.loc[np.where(y_all == '8')[0]]  # all digit 8
X_9 = X_all.loc[np.where(y_all == '9')[0]]  # all digit 9





In [9]:
y0 = np.zeros(X_0.shape[0])  # class 0 label
y0

array([0., 0., 0., ..., 0., 0., 0.])

In [10]:
y1 = np.ones(X_1.shape[0])  # class 1 label
y1

array([1., 1., 1., ..., 1., 1., 1.])

In [11]:
X = np.concatenate((X_0, X_1, X_2, X_3, X_4, X_5, X_6, X_7, X_8, X_9), axis=0)
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
y = np.concatenate((y0, y1), axis=0)
y

array([0., 0., 0., ..., 1., 1., 1.])

# Phân chia dữ luyện huấn luyện, kiểm tra

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y_all, test_size=10000)

In [14]:
print("Training set: {:d} samples".format(X_train.shape[0]))

Training set: 60000 samples


In [15]:
model = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial')  # C is inverse of lamda
model.fit(X_train, y_train)

C:\Users\taqua\miniconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=100000.0, multi_class='multinomial')

In [16]:
y_pred = model.predict(X_test)
print("Accuracy %.2f %%" % (100 * accuracy_score(y_test, y_pred)))

Accuracy 92.18 %


In [17]:
# This function visualizes filters in matrix A. Each column of A is a
# filter. We will reshape each column into a square image and visualizes
# on each cell of the visualization panel.
# All other parameters are optional, usually you do not need to worry
# about it.
# opt_normalize: whether we need to normalize the filter so that all of
# them can have similar contrast. Default value is true.
# opt_graycolor: whether we use gray as the heat map. Default is true.
# opt_colmajor: you can switch convention to row major for A. In that
# case, each row of A is a filter. Default value is false.
# source: https://github.com/tsaith/ufldl_tutorial

def display_network(A, m=-1, n=-1):
    opt_normalize = True
    opt_graycolor = True

    # Rescale
    A = A - np.average(A)

    # Compute rows & cols
    (row, col) = A.shape
    sz = int(np.ceil(np.sqrt(row)))
    buf = 1
    if m < 0 or n < 0:
        n = np.ceil(np.sqrt(col))
        m = np.ceil(col / n)

    image = np.ones(shape=(buf + m * (sz + buf), buf + n * (sz + buf)))

    if not opt_graycolor:
        image *= 0.1

    k = 0

    for i in range(int(m)):
        for j in range(int(n)):
            if k >= col:
                continue

            clim = np.max(np.abs(A[:, k]))

            if opt_normalize:
                image[buf + i * (sz + buf):buf + i * (sz + buf) + sz, buf + j * (sz + buf):buf + j * (sz + buf) + sz] = \
                    A[:, k].reshape(sz, sz) / clim
            else:
                image[buf + i * (sz + buf):buf + i * (sz + buf) + sz, buf + j * (sz + buf):buf + j * (sz + buf) + sz] = \
                    A[:, k].reshape(sz, sz) / np.max(np.abs(A))
            k += 1

    return image


def display_color_network(A):
    """
    # display receptive field(s) or basis vector(s) for image patches
    #
    # A         the basis, with patches as column vectors

    # In case the midpoint is not set at 0, we shift it dynamically

    :param A:
    :param file:
    :return:
    """
    if np.min(A) >= 0:
        A = A - np.mean(A)

    cols = np.round(np.sqrt(A.shape[1]))

    channel_size = A.shape[0] / 3
    dim = np.sqrt(channel_size)
    dimp = dim + 1
    rows = np.ceil(A.shape[1] / cols)

    B = A[0:channel_size, :]
    C = A[channel_size:2 * channel_size, :]
    D = A[2 * channel_size:3 * channel_size, :]

    B = B / np.max(np.abs(B))
    C = C / np.max(np.abs(C))
    D = D / np.max(np.abs(D))

    # Initialization of the image
    image = np.ones(shape=(dim * rows + rows - 1, dim * cols + cols - 1, 3))

    for i in range(int(rows)):
        for j in range(int(cols)):
            # This sets the patch
            image[i * dimp:i * dimp + dim, j * dimp:j * dimp + dim, 0] = B[:, i * cols + j].reshape(dim, dim)
            image[i * dimp:i * dimp + dim, j * dimp:j * dimp + dim, 1] = C[:, i * cols + j].reshape(dim, dim)
            image[i * dimp:i * dimp + dim, j * dimp:j * dimp + dim, 2] = D[:, i * cols + j].reshape(dim, dim)

    image = (image + 1) / 2

    #PIL.Image.fromarray(np.uint8(image * 255), 'RGB').save(filename)

    return image

In [18]:
from matplotlib.backends.backend_pdf import PdfPages
mis = np.where((y_pred - y_test) != 0)[0]
print(mis)
Xmis = X_test[mis, :]

TypeError: Object with dtype category cannot perform the numpy op subtract

# Tìm những ảnh bị phân loại sai và hiển thị chúng

In [ ]:
filename = 'mnist_mis.pdf'

with PdfPages(filename) as pdf:
    plt.axis('off')
    A = display_network(Xmis.T, 1, 1)
    f2 = plt.imshow(A, interpolation='nearest')
    plt.gray()
    pdf.savefig(bbox_inches='tight')
    plt.show()