In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
mnist = fetch_openml('mnist_784')

C:\Users\taqua\miniconda3\lib\site-packages\sklearn\datasets\_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
N, d = mnist.data.shape
print("Total {:d} samples, each has {:d} pixels.".format(N, d))

Total 70000 samples, each has 784 pixels.


In [4]:
X_all = mnist.data
X_all

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0           0.0       0.0       0.0       0.0       0.0  
1           0.0       0.0       0.0       0.0       0.0  
2           0.0       0.0       0.0       0.0       0.0  
3           0.0       0.0       0.0       0.0       0.0  
4           0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69995       0.0       0.0       0.0       0.0       0.0  
69996       0.0       0.0       0.0       0.0       0.0  
69997       0.0       0.0       0.0       0.0       0.0  
69998       0.0       0.0       0.0       0.0       0.0  
69999       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [5]:
y_all = mnist.target
y_all

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [7]:
X_0 = X_all.loc[np.where(y_all == '0')[0]] # all digit 0
X_0

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
21        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
34        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
37        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
51        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69952     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69962     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69964     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69983     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69993     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
21         0.0  ...       0.0       0.0       0.0       0.0       0.0   
34         0.0  ...       0.0       0.0       0.0       0.0       0.0   
37         0.0  ...       0.0       0.0       0.0       0.0       0.0   
51         0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69952      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69962      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69964      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69983      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69993      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
1           0.0       0.0       0.0       0.0       0.0  
21          0.0       0.0       0.0       0.0       0.0  
34          0.0       0.0       0.0       0.0       0.0  
37          0.0       0.0       0.0       0.0       0.0  
51          0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69952       0.0       0.0       0.0       0.0       0.0  
69962       0.0       0.0       0.0       0.0       0.0  
69964       0.0       0.0       0.0       0.0       0.0  
69983       0.0       0.0       0.0       0.0       0.0  
69993       0.0       0.0       0.0       0.0       0.0  

[6903 rows x 784 columns]

In [8]:
X_1 = X_all.loc[np.where(y_all == '1')[0]] # all digit 1
X_1

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
6         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
8         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
14        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
23        0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69956     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69969     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69978     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69984     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69994     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
6          0.0  ...       0.0       0.0       0.0       0.0       0.0   
8          0.0  ...       0.0       0.0       0.0       0.0       0.0   
14         0.0  ...       0.0       0.0       0.0       0.0       0.0   
23         0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69956      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69969      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69978      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69984      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69994      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
3           0.0       0.0       0.0       0.0       0.0  
6           0.0       0.0       0.0       0.0       0.0  
8           0.0       0.0       0.0       0.0       0.0  
14          0.0       0.0       0.0       0.0       0.0  
23          0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
69956       0.0       0.0       0.0       0.0       0.0  
69969       0.0       0.0       0.0       0.0       0.0  
69978       0.0       0.0       0.0       0.0       0.0  
69984       0.0       0.0       0.0       0.0       0.0  
69994       0.0       0.0       0.0       0.0       0.0  

[7877 rows x 784 columns]

In [9]:
y0 = np.zeros(X_0.shape[0]) # class 0 label
y0

array([0., 0., 0., ..., 0., 0., 0.])

In [11]:
y1 = np.ones(X_1.shape[0]) # class 1 label
y1

array([1., 1., 1., ..., 1., 1., 1.])

In [12]:
X = np.concatenate((X_0, X_1), axis=0) # all digits 0 and 1
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
y = np.concatenate((y0, y1), axis=0) # all labels 0 and 1
y

array([0., 0., 0., ..., 1., 1., 1.])

# Phân chia dữ luyện huấn luyện, kiểm tra

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [16]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
y_train

array([0., 0., 1., ..., 0., 1., 1.])

In [19]:
y_test

array([0., 1., 0., ..., 0., 1., 1.])

# Xây dựng mô hình Logistic Regression

trên tập huấn luyện và dự đoán nhãn của các điểm trong tập kiểm tra.

Kết quả này được so sánh với nhãn thực sự của mỗi điểm dữ liệu để tính độ chính xác của bộ phân loại

In [20]:
model = LogisticRegression(C=1e5, solver='lbfgs', multi_class='multinomial') # C is inverse of lamda
model.fit(X_train, y_train)

LogisticRegression(C=100000.0, multi_class='multinomial')

In [21]:
y_pred = model.predict(X_test)
print("Accuracy %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy 99.90 %
