# Q1: Create 1D from 0 to 9 => b

In [4]:
import numpy as np
a = np.arange(0, 10, 1) # numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q2: Create 3x3 numpy array with all True values => d

In [11]:
import numpy as np
a = np.full((3, 3), True, dtype=bool) # numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
a1 = np.ones((3, 3), dtype=bool) # numpy.ones(shape, dtype=None, order='C', *, like=None)
a2 = np.ones((3, 3)) > 0
a2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Q3: Result of the code => a

In [6]:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] # Lấy các số chia cho 2 mà dư 1

array([1, 3, 5, 7, 9])

# Q4: Result of the code

In [7]:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1 # Lấy các số chia cho 2 mà dư 1 và gán = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Q5: Result of the code => b

In [8]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1) # arr.reshape(2, -1) => arr.reshape(2, 5)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Q6: Result of the code => c

In [9]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1) # Lấy mảng từ 0-9 và chuyển thành mảng 2 chiều
arr2 = np.repeat(1, 10).reshape(2, -1) # Lấy mảng gồm 10 số 1 và chuyển thành mảng 2 chiều
c = np.concatenate([arr1, arr2], axis=0) # axis = 0 => nối theo chiều dọc
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Q7: Result of the code => a

In [12]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1) # axis = 1 => nối theo chiều ngang
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Q8: Result of the code => b

In [15]:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
