# Q1: Create 1D from 0 to 9 => b

In [4]:
import numpy as np
a = np.arange(0, 10, 1) # numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Q2: Create 3x3 numpy array with all True values => c

In [5]:
import numpy as np
a = np.full((3, 3), True, dtype=bool) # numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Q3: Result of the code => a

In [6]:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] # Lấy các số chia cho 2 mà dư 1

array([1, 3, 5, 7, 9])

# Q4: Replace all odd numbers in arr with -1 => b